# Railway Configuration for Keycloak
# Deploy Version: 1.2
# Date: 2025-10-22
# Added: Persistent volume for Keycloak data directory

[build]
# Use Dockerfile for build

[deploy]
startCommand = "/opt/keycloak/bin/kc.sh start-dev"
healthcheckPath = "/health/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/opt/keycloak/data"
name = "keycloak-data"
